# Generated by Django 4.1.7 on 2023-06-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='kunasyl', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
