# Generated by Django 4.1.7 on 2023-06-25 19:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_phoneverification_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
