# Generated by Django 4.1.7 on 2023-06-29 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_rename_user_product_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='product_id',
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_favorites', to='products.product', verbose_name='Товар')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Понравившийся товар',
                'verbose_name_plural': 'Понравившиеся товары',
                'ordering': ('-created_at',),
            },
        ),
    ]
